### ISSUE TITLE
やること

### ISSUE THREAD

**Issue by sasakisyota** [sasakisyota/mvc-sample-ios#1]
- [x] Xcodeで新規プロジェクトを作成、名前はmvc-sample-ios
- [x] GitHubのリポジトリにpushする（ commitは適度に行う ）
- [x] TableViewを用いて「牛乳を買う」「掃除をする」「アプリ開発の勉強をする」を表示させる
- [x] Alamofireライブラリを用いてQiita APIからデータを取得し、print()でコンソールに表示させる
- [x] TableViewに Qiita APIのJSONデータ内のtitleをリストに表示する
- [x] 2で作成したアプリをCocoa MVCアーキテクチャを用いてリファクタリングする
- [x] Qiitaの記事を書くこと
何をやったか
手順
理解していること
理解していないこと

**Comment by Fuyan777** [comment]
<img width="1440" alt="スクリーンショット 2021-09-25 16 58 23" src="https://user-images.githubusercontent.com/29572313/134763923-828d9d0c-6ae2-4990-bd8b-15e0d5b1bfc9.png">


https://github.com/sasakisyota/mvc-sample-ios/blob/5d1871331ed4fab561363f9631f42979302a686a/mvc-sample-ios/ViewController.swift#L10-L15

**Comment by sasakisyota** [comment]
https://github.com/sasakisyota/mvc-sample-ios/blob/5d1871331ed4fab561363f9631f42979302a686a/mvc-sample-ios/ViewController.swift#L10-L15

**Comment by sasakisyota** [comment]
<img width="496" alt="スクリーンショット 2021-09-26 10 07 40" src="https://user-images.githubusercontent.com/62680416/134789697-7413b0a4-8d22-4648-95c7-485feca6ac19.png">

**Comment by Fuyan777** [comment]
@sasakisyota 
今TableViewをセクション分けでセルを表示しているけど、
以下のようなセクションなしでセルを表示できるように修正してほしい！

<img width="171" alt="スクリーンショット 2021-09-26 10 53 34" src="https://user-images.githubusercontent.com/29572313/134790505-88c790a8-5167-4c75-ad85-eb377a6ae646.png">

**Comment by Fuyan777** [comment]
@sasakisyota 
マージした後、
mainのブランチに戻る必要がある！
`git checkout main`

mainに移動できたことを確認したら、リモートの変更をローカルにも更新させる処理を行う。
`git pull`

上記ができたら、報告して！

**Comment by sasakisyota** [comment]
出来ました！大丈夫そうですか？

**Comment by Fuyan777** [comment]
できたら、手順4を進めよう！

**Comment by sasakisyota** [comment]
# 9/26(日)

## やったこと（時間）
- TableViewのレイアウト修正（1h）
- ブランチ、プルリクエスト、マージの実行 (1h)
- alamofireをインストール (1h)
- alamofireでAPI通信処理 (3h)
- エラーの処理 (2h)

## 次やること
エラーの処理の続き
Alamofireで取得したQiitaのデータをTableViewに表示する
## 困っていること
エラーの対処の仕方が分からない（どのくらい時間をかけてやっていいのか、どの部分を直すのか） etc

**Comment by Fuyan777** [comment]
> エラーの対処の仕方が分からない（どのくらい時間をかけてやっていいのか、どの部分を直すのか） etc

エラーに悩む時間は10分までにしよう！
それ以降は、すぐ質問しよう！（むしろ質問する際に文章や内容整理する方が大事）

### 質問する時に気をつけること

以降の項目は質問する際に共有しておくと親切👍

・エラー発生までの手順を詳細に説明できるか？
→「ボタン押したらエラーなりました」だとお互い苦しい状況に😭

・エラー発生した後に自分はどのような操作を行ったか説明できるか？
→エラー文だけ共有されても、質問された側は調査にかなり時間がかかってしまう

**Comment by Fuyan777** [comment]
## 追加タスク

Qiitaの記事を書くこと
- 何をやったか
- 手順
- 理解していること
- 理解していないこと

**Comment by sasakisyota** [comment]
# MVCモデル 
モデル、ビュー、コントローラーの頭文字を取ったユーザーインターフェイスと内部データを分けるデザ　　　 
インパターンの一つ。アプリケーション設計の機能を整理するための概念。機能によってプログラムの 
中身を分けて記述すること。アプリケーション全体のコードを管理するための考え方。
- M(モデル)...システムの本体、データやビジネスロジックを処理する。ユーザーアクセスにより促された処理をデータベースにアクセスし、操作・参照して必要な値に取り出し、または変化して、インターフェースに通知する。
- V(ビュー)...ユーザーインターフェイスの部分を担当。使用者（ユーザー）とサイトとのインターフェイス（接点）でもあり、レイアウトやメニュー、ボタンの操作性など、画面表示やボタンの操作性もビューの役割。
- C(コントローラー)...MVCのコントローラーとはユーザーの入力に基づき、モデルとビューを制御する役目を担う部分。コントローラーはモデルとビューの橋渡しであり、繋ぎとしての役目に徹する。
### メリット
- 効率が上がる...役割や機能別でコードを分けることにより、開発するときも、変更するときも、保守するときも、「このコードはどこの関連か」と迷うことがなくなる。
- 保守性を確保できる...各モジュールで役割分担していることにより、保守性が上がり、品質も向上する。ビューにバグが発生したとしても修正はビューだけに止まり、モデルやコントローラーにはほとんど影響がない。
- コードを再利用しやすい...一度書いたコードをもう一度使える。再利用は、すでにそのコードが機能することが検証されているので、信頼性が増す。
- 機能を分割できる...独立性が高く、別れている分野ごとに専門性に特化しているため、バグやトラブルが起こっても各機能への影響が少なく、柔軟に対応できる。
- わかりやすい...ロジックコードはモデルに、表示に関することはビューに、モデル・ビュー・ユーザーを繋ぐことはコントローラーに、とコードを整理することにより、よりわかりやすくコードを管理できる。
### デメリット
- 大まかな役割分担では機能しない... 役割の分担を疎かにすると、MVCのメリットを享受できなくなる。おおよその役割分担では、プログラムの構造が歪になってしまう危険性があるから。
- 制約がかかる...オブジェクト間のやりとりに制約がかかり、コードを柔軟に記述できなくなる。
- 分担に時間がかかる...機能にあった役割分担ができていないと、MVCのメリットが享受できなくなる。役割を考える必要があるため、詳細な設計を行う必要もあり、そのために作業工数が増えることもある。

**Comment by sasakisyota** [comment]
### ソフトウェアアーキテクチャパターン
開発する際のルールのようなもの。開発する際のフォルダ構成やファイル名等バラつきがあり、ソースコードが属人化してしまうこと。作った本人しかわからないソースコードは良くないソースコード。決められたルールを作ることで開発の時間短縮、結果開発コストの削減になる。

**Comment by sasakisyota** [comment]
# MVVMモデル
ユーザーが入力した情報と、格納したデータをデータバインディングにて自動的に処理していくもの。
- M(モデル)、V(ビュー)...MVCと役割は同じ
- VM(View Model)...ModelとViewを紐付ける接着剤のような役割を果たす。ViewModelで変更されたデータは即座にViewに反映される。
### データバインディングとは
ViewとViewModelを結びつける仕組みのこと。データバインディングの特徴は、ViewとViewModelどちらかで値が書き変われば、値が変化するたびにViewとViewModel、両方の値が変更されるという点。つまり、ユーザーが画面上でなんらかの処理した場合でも、コンピュータ上やサーバー上で何らかの処理があった場合でもViewとViewModelそれぞれに反映されるということ。

**Comment by Fuyan777** [comment]
@sasakisyota 
余裕があったら、MVCモデルとMVVMモデルのグラフ化してみるとさらに良いかも！
結局、アーキテクチャ関連って最終的にグラフ化しないといけなかったりするからね🤔

追記
MVCモデルグラフ化してるのめっちゃ良いな！！

**Comment by Fuyan777** [comment]
> データバインディングとは
> ViewとViewModelを結びつける仕組みのこと。

アーキテクチャ以外にも変数とかも同じことが言える！例えばSwiftUIの`@State`とかも同じデータバインディングを用いられている！

**Comment by sasakisyota** [comment]
> > データバインディングとは
> 
> > ViewとViewModelを結びつける仕組みのこと。
> 
> 
> 
> アーキテクチャ以外にも変数とかも同じことが言える！例えばSwiftUIの`@State`とかも同じデータバインディングを用いられている！

前に解説してくれたやつですね！分かりました！

**Comment by sasakisyota** [comment]
# オブジェクト指向
プログラムを設計するときの考えの一つ。「プロパティ」と「メソッド」をひとまとめにして「クラス」を作り、それを元に、「オブジェクト」を作成する手法。ルールのように明確に定められているわけではなく、プログラムを設計するときのベースとなる考え方。
### クラス
オブジェクトを作成するための設計図。
### プロパティ
オブジェクトが持つ性質や属性のこと。プログラム上では、クラスの中にプロパティの変数をあらかじめ設けておく。
### メソッド
オブジェクト内のデータを操作するためのふるまいをまとめたもの。プログラム中では、クラスの中にメソッドをあらかじめ設けておく。
### オブジェクト（インスタンス）
設計図であるクラスから作成した実体。ひとつのクラスを元に、複数のオブジェクトを作成できる。
### メリット
プログラムが整理されて冗長なコードがなくなるので、開発工数が削減できたり、複数人で開発するときに分担しやすくなったり、予期しないバグを防ぐことができる。
### デメリット
プログラム設計時により高いスキルを要することや、設計に時間がかかる。
<img width="661" alt="スクリーンショット 2021-10-07 17 26 58" src="https://user-images.githubusercontent.com/62680416/136347961-bdb07a4a-3b98-4688-92d4-0ec98a8cb808.png">
