### ISSUE TITLE
手順４

### ISSUE THREAD

**Issue by sasakisyota** [sasakisyota/mvc-sample-ios#4]
### Alamofireをインストール
- [x] CocoaPodsを使用してインストール
- [x] ターミナルでPodfileの作成
### Codableを使ってJSONを変換する
- [x] QiitaAPIから取得したデータをJSONで受け取って、Codableで構造体に変換する
### AlamofireでAPI通信をする
- [x] Alamofireをプロジェクトで使えるようにする
### TableViewに表示する
- [x] 取得したQiitaのデータをTableViewに表示する

**Comment by Fuyan777** [comment]
CocoaPodsを使用してインストールについて
- pod installすると、xcworkspaceっていう白いファイルが生成されるので、これを起動して作業する必要がある
  - （青のプロジェクトファイルだとpodのライブラリが使えないため）

<img width="233" alt="スクリーンショット 2021-09-26 17 05 40" src="https://user-images.githubusercontent.com/29572313/134799258-e9e186c8-804f-41c3-b769-77fd619deedd.png">
