### ISSUE TITLE
"[<UIViewController 0x155009ad0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key articleListTableView."

### ISSUE THREAD

**Issue by sasakisyota** [sasakisyota/mvc-sample-ios#6]
<img width="1590" alt="スクリーンショット 2021-09-27 1 02 42" src="https://user-images.githubusercontent.com/62680416/134815284-8f86c8b1-0066-4361-903c-037dd122bc1d.png">

**Comment by Fuyan777** [comment]
どのコードを追加したら、エラーが出てくるってところまで書いておくと良いかも！
エラー発生までの操作手順とか

**Comment by sasakisyota** [comment]
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value のエラーを解決するためにTableViewにOutlet接続をしました。その後、このエラーが消えたのでビルドしてみるとコードにはエラーが書いてないのですが、ビルドした際にAppDelegateにこのエラーが出てしまいました。

**Comment by Fuyan777** [comment]
エラー内容って調べた？？

**Comment by sasakisyota** [comment]
調べました！storyboardの方にコードと接続されていないのが原因だと思って、もう一度storyboardを新しく作り直してtableviewを作成したのですがうまく接続されないで同じエラーが出る状況です...
それからは何が分からないのか分からなくなった状態です。
