### ISSUE TITLE
手順6/Cocoa MVCアーキテクチャを用いてリファクタリングする

### ISSUE THREAD

**Issue by sasakisyota** [sasakisyota/mvc-sample-ios#8]
### ViewControllerを実装する
- [x] 1...Modelに処理を依頼する
- [x] 4...Modelの変更を検知する
### Modelを実装する
- [x] 2...データを処理する
- [x] 3...変更を通知する
- [x] 5...描画指示
### Viewを実装する
- [x] 6...描画処理を行う
![mvc-sample-ios](https://user-images.githubusercontent.com/62680416/135504978-e838707d-8fd4-401f-b8bc-63f669e4cb75.jpg)

**Comment by sasakisyota** [comment]
Cocoa MVCアーキテクチャを用いてリファクタリングする

**Comment by Fuyan777** [comment]
名前こっちの方がわかりやすい気がする！
→ 手順6/Cocoa MVCアーキテクチャを用いてリファクタリングする

**Comment by Fuyan777** [comment]
手順1〜6をやる上で、具体的にどのような作業が必要か考えよう！

例えば、modelの実装に必要な作業ってなんだろう？？
まずModelのクラスを作るのに、Swiftファイルを作成する必要があるよね！？
次に作成したModelクラスの中には何が必要だろう？データ処理とか、変更通知のための処理ってどのようなコードで実現できるだろうか？

**Comment by Fuyan777** [comment]
公式のCocoa MVC
https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/MVC.html

**Comment by sasakisyota** [comment]
## Cocoa MVCアーキテクチャを用いてリファクタリングする
### ViewControllerを実装する
- [x] ...Controllerファイルを作成する
- [x] ...AllArticleクラスをインスタンス化(let allArticle = AllArticle())して、AllArticleクラスが持ってい QittaAPIのデータをTableViewに描写していく
- [x] ...ViewControllerを配置する
### Modelを実装する
- [x] ...Modelのファイルを作成する
- [x] ...作成したファイルの中に記事単体の情報を持つクラス（データ型）のArticle.swift、全てのデータを配列に入れてAllArticleクラスをインスタンス化(var list = [Article]())
### Viewを実装する
- [x] ...Viewのファイルを作成する
- [x] ...TableViewを配置する

**Comment by Fuyan777** [comment]
実装しながらで良いんだけど、いくつかコメント！

> Viewを実装する
>  ...Viewのファイルを作成する
>  ...TableViewを配置する

TableViewとTableViewControllerの違いってなんだろう？？


> Viewのファイルを作成する

どんな名前のファイルを作成するかも明記しておくと良いかな！
名前をつけるのはかなり重要なので！

**Comment by sasakisyota** [comment]
### TableView
配列などで格納されたデータをリストとして画面に表示したい場合に使うUI。今回の場合はQiita APIから取得したデータを画面にリストとして表示している。
### TableViewController
ビュー同士の動きの連携や画面遷移、まとまった機能をつなげるなどアプリの流れに関わる部分を実装する。
---
機能を見せる   = View(ビュー)
機能をつなげる = Controller(コントローラ)
機能を実現する = Model(モデル)
<img width="454" alt="スクリーンショット 2021-10-06 1 33 56" src="https://user-images.githubusercontent.com/62680416/136064964-0319670f-dcc6-462a-8675-a44df49afabf.png">
